run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/user/speed-test-go
